# Numpy tutorial

Welcome!

Pre-requisites for this tutorial:
- Basic python (variables, types, lists, dicts, etc.) 

## Installing  and importing Numpy

Please view official documentation here: https://numpy.org/

In [ ]:
# Run this cell to install numpy. Can alternately be run on a command line
!pip install numpy

In [1]:
import numpy as np

## Creating a numpy array

Numpy arrays can be created in a number of ways. One of the ways is by using a python list such as [1,2,3].

In [ ]:
list_of_numbers = [1,2,3]
numpy_array_of_list = np.array(list_of_numbers)

print("The numpy array is ", numpy_array_of_list)
print("The type of a numpy array is ", type(numpy_array_of_list))

Here are some other ways to create numpy arrays

In [ ]:
# To create an array of zeros
zeros_array = np.zeros(3)
print(f"Array of zeros: {zeros_array}")

# To create an array of ones
ones_array = np.ones(5)
print(f"Array of ones: {ones_array}")

# To create an array from 15 to 25 with step size 2. Works similar to python list slicing.
range_array = np.arange(15, 25, 2)
print(f"Array from range [15,25) with step size 2: {range_array}")

# Note: the 'start' and 'step' parameters are optional. 
range_array_only_stop = np.arange(6)
print(f"Array from [0,6): {range_array_only_stop}")

# To create an array with 6 elements in the range [13,15] which are evenly spaced
linspace_array = np.linspace(13, 15, num=6)
print(f"Array of 6 elements in range [13,15]: {linspace_array}")

# We can also make the range exclude the endpoint. This is an array with 6 elements in the range [13,15)
linspace_array_exclude_endpoint = np.linspace(13, 15, num=6, endpoint=False)
print(f"Array of 6 elements in range [13,15): {linspace_array_exclude_endpoint}")

We can also create arrays of different types.
- To view a list of all dtypes: https://numpy.org/doc/2.1/reference/arrays.dtypes.html
- Usually, np.int32 and np.float64 are used.

In [5]:
float_array = np.ones(6, dtype=np.float64)
print(f"Float array: {float_array}")

Float array: [1. 1. 1. 1. 1. 1.]


## Indexing and Slicing

This works similar to regular Python lists.

In [ ]:
a = np.array([4,7,2,3,1,6,4,9,0,2,3])
print(f"The element at index 3 is {a[3]}")
print(f"The array from index 2 to 5 (exluding 5) is {a[2:5]}")
print(f"The array from index 3 to 7 with step size 2 is {a[3:7:2]}")

What if you want elements of indices 2,6,4, and 7?

Custom indexing is supported in numpy.

In [ ]:
a = np.array([4,7,2,3,1,6,4,9,0,2,3])
print(f"Elements at indices 2,6,4, and 7: {a[[2,6,4,7]]}")

Arrays can be modified. See below for examples.

In [ ]:
a = np.array([4,7,2,3,1,6,4,9,0,2,3])
print(f"Array: {a}")

# To change element at index 3 to 57
a[3] = 57
print(f"After changing index 3 to 57: {a}")

# Changing indices 4,6,7 to 123
a[[4,6,7]] = 123
print(f"After changing indices 4,6,7 to 123: {a}")

#### Masks

- Masks are useful if you want all elements/numbers in an array that satisfy a particular condition.
- Masks are a boolean numpy array where the value at an index 'True' if the boolean condition is satisfied and 'False' otherwise.
- Common boolean operators should be used as follows (this is different from regular python syntax):
    * & (and)
    * | (or)
    * ~ (not)
- Parentheses are required when using boolean operators such as '&' and '|'. If not you will likely get an error as follows:
    * `ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()`

For example, what if we want the indices of all elements that are greater than 3. The boolean condition here is if an element is greater than 3.

In [ ]:
# To get indices of all elements greater than 3
a = np.array([4,7,2,3,1,6,4,9,0,2,3])
mask = a > 3
print(f"Mask for elements >3 in array: {mask}")
print(f"Elements greater than 3: {a[mask]}")

Masking can sometimes be done in one line of code, without creating a variable called 'mask'.

In [ ]:
a = np.array([4,7,2,3,1,6,4,9,0,2,3])
print(f"Elements lesser than or equal to 6 in the array: {a[a <= 6]}")

Here are more ways boolean conditions can be formulated.

In [ ]:
a = np.array([4,7,2,3,1,6,4,9,0,2,3])
print(f"Array: {a}")

# To get all elements not equal to 4. There are two ways to do this.
print(f"All elements not equal to 4: {a[a != 4]}")
print(f"All elements not equal to 4: {a[~(a == 4)]}")

# To get all elements between 3 and 7 exluding 7, i.e. in the interval [3,7) i.e. >=3 and <7
print(f"All elements in range [3,7): {a[(a >= 3) & (a < 7)]}")

# To get all elements not greater than 3 (i.e. <=3) or greater than 7
print(f"All elements that are in range (-inf,3] u (7,inf): {a[~(a > 3) | (a > 7)]}")

## Shape

Numpy arrays don't have to be a 1-dimensional list.

The can be 2,3, or multiple dimensions. A 2-d numpy array would be a matrix. A 3-d would be like stacking multiple matrices together, like a cube.

In [ ]:
# To create a 2-d array from a list of lists
a = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(f"2-d array from list: \n{a}")
print()

# To create a 3-d array with ones that is like stacking three 5x7 matrices together
a = np.ones(shape=(3,5,7))
print(f"3-d array of ones: \n{a}")

## Linear Algebra

Numpy can also be used to perform linear algebra operations.

In [7]:
# To create a diagonal matrix using a list or array
diagonal_matrix = np.diag([1,2,3,4])
print(f"Diagonal matrix: \n{diagonal_matrix}")
print()

# To create an identity matrix
identity_matrix = np.eye(3)
print(f"Identity matrix of size 3: \n{identity_matrix}")

Diagonal matrix: 
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]

Identity matrix of size 3: 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [8]:
# To perform a matrix multiplication, there are two ways

A = np.array([   # 2x3 matrix
    [1,2,3],
    [4,5,6]
])

B = np.array([   # 3x4 matrix
    [1,2,3,1],
    [4,5,6,1],
    [7,8,9,1]
])

print(f"A x B = \n{np.matmul(A, B)}\n")
print(f"A x B = \n{A @ B}")

A x B = 
[[30 36 42  6]
 [66 81 96 15]]

A x B = 
[[30 36 42  6]
 [66 81 96 15]]


In [ ]:
# If the matrix multiplication is invalid (such as if the dimensions don't match) we get the following error
# THIS WILL THROW AN ERROR
print(f"B x A = {B @ A}")

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 4)